# Generated by Django 5.2.16 on 2026-07-08 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TizimSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejim', models.CharField(choices=[('biznes', 'Kompaniya / Ishchilar'), ('talim', "O'quv markazi / O'quvchilar")], default='biznes', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoydalanuvchiProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ismi familyasi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Rasm (Avatar)')),
                ('joriy_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('joriy_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('oxirgi_yangilanish', models.DateTimeField(auto_now=True)),
                ('vaqt_boshlanishi', models.TimeField(default='08:00:00', verbose_name='Boshlanish vaqti')),
                ('vaqt_yakuni', models.TimeField(default='17:00:00', verbose_name='Tugash vaqti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('keldi', 'Keldi / Kuzatish shartmas'), ('kelmadi', 'Kelmagan / Qidirilmoqda')], default='kelmadi', max_length=15)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlari', to='ilova.foydalanuvchiprofil')),
            ],
        ),
        migrations.CreateModel(
            name='HarakatTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vaqt', models.DateTimeField(verbose_name='GPS olingan vaqt')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarixi', to='ilova.foydalanuvchiprofil')),
            ],
            options={
                'ordering': ['vaqt'],
            },
        ),
    ]
